import datetime
import os
import shutil
import subprocess

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import NameOID


def mkcert_status() -> dict:
    """Check mkcert availability and CA installation status."""
    path = shutil.which("mkcert")
    if not path:
        return {"installed": False, "ca_installed": False}

    # Check if local CA is installed
    try:
        result = subprocess.run(
            ["mkcert", "-CAROOT"], capture_output=True, text=True, timeout=5
        )
        ca_root = result.stdout.strip()
        ca_installed = ca_root and os.path.isdir(ca_root) and os.path.exists(
            os.path.join(ca_root, "rootCA.pem")
        )
    except (subprocess.TimeoutExpired, OSError):
        ca_installed = False

    return {"installed": True, "ca_installed": ca_installed, "path": path}


def install_mkcert() -> dict:
    """Install mkcert via brew and set up the local CA."""
    status = mkcert_status()

    if not status["installed"]:
        # Try to install via brew
        if not shutil.which("brew"):
            return {"success": False, "error": "Homebrew not found. Install mkcert manually: https://github.com/FiloSottile/mkcert"}

        try:
            result = subprocess.run(
                ["brew", "install", "mkcert"],
                capture_output=True, text=True, timeout=120,
            )
            if result.returncode != 0:
                return {"success": False, "error": f"brew install failed: {result.stderr[-300:]}"}
        except subprocess.TimeoutExpired:
            return {"success": False, "error": "brew install timed out"}

    # Install the local CA (adds to system keychain - may prompt for password)
    try:
        result = subprocess.run(
            ["mkcert", "-install"],
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode != 0 and "already" not in result.stderr.lower():
            return {"success": False, "error": f"mkcert -install failed: {result.stderr[-300:]}"}
    except subprocess.TimeoutExpired:
        return {"success": False, "error": "mkcert -install timed out"}

    return {"success": True}


def generate_cert(domain: str, certs_dir: str) -> tuple[str, str, bool]:
    """Generate an SSL certificate for the given domain.

    Tries mkcert first (browser-trusted), falls back to self-signed.
    Returns (cert_path, key_path, is_trusted).
    """
    cert_path = os.path.join(certs_dir, f"{domain}.crt")
    key_path = os.path.join(certs_dir, f"{domain}.key")

    # Reuse existing cert if present
    if os.path.exists(cert_path) and os.path.exists(key_path):
        # Check if it was generated by mkcert (mkcert certs have a specific issuer)
        is_trusted = _is_mkcert_cert(cert_path)
        return cert_path, key_path, is_trusted

    # Try mkcert first
    status = mkcert_status()
    if status["installed"] and status["ca_installed"]:
        try:
            result = subprocess.run(
                [
                    "mkcert",
                    "-cert-file", cert_path,
                    "-key-file", key_path,
                    domain,
                    f"*.{domain}",
                ],
                capture_output=True, text=True, timeout=15,
            )
            if result.returncode == 0 and os.path.exists(cert_path):
                return cert_path, key_path, True
        except (subprocess.TimeoutExpired, OSError):
            pass

    # Fallback: self-signed cert
    _generate_self_signed(domain, cert_path, key_path)
    return cert_path, key_path, False


def _is_mkcert_cert(cert_path: str) -> bool:
    """Check if a certificate was generated by mkcert."""
    try:
        with open(cert_path, "rb") as f:
            cert = x509.load_pem_x509_certificate(f.read())
        issuer_cn = cert.issuer.get_attributes_for_oid(NameOID.ORGANIZATION_NAME)
        return any("mkcert" in attr.value.lower() for attr in issuer_cn)
    except Exception:
        return False


def _generate_self_signed(domain: str, cert_path: str, key_path: str):
    """Generate a self-signed SSL certificate."""
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)

    subject = issuer = x509.Name(
        [x509.NameAttribute(NameOID.COMMON_NAME, domain)]
    )

    now = datetime.datetime.now(datetime.timezone.utc)
    cert = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(issuer)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now)
        .not_valid_after(now + datetime.timedelta(days=365))
        .add_extension(
            x509.SubjectAlternativeName([x509.DNSName(domain)]),
            critical=False,
        )
        .sign(key, hashes.SHA256())
    )

    with open(key_path, "wb") as f:
        f.write(
            key.private_bytes(
                serialization.Encoding.PEM,
                serialization.PrivateFormat.TraditionalOpenSSL,
                serialization.NoEncryption(),
            )
        )

    with open(cert_path, "wb") as f:
        f.write(cert.public_bytes(serialization.Encoding.PEM))
